import { SiteHeader } from "@/components/site-header";
import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { fontMono, fontSans } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background flex flex-col min-h-svh overscroll-none font-sans antialiased",
          fontSans.variable,
          fontMono.variable
        )}
      >
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
